### ISSUE TITLE
error running FilterBunches

### ISSUE THREAD

**Issue by tomeichlersmith** [tomeichlersmith/hps-prod#2]
```
hpsmc.job:INFO Executing 'filter_bunches' with command: java -Xmx1g -XX:+UseSerialGC -Dorg.lcsim.cacheDir=/export/scratch/tmp.CFlQcDiXKn/scratch -cp /usr/local/hps/java/distribution/target/hps-distribution-5.2-SNAPSHOT-bin.jar org.hps.util.FilterMCBunches -e 250 idm_rot.slcio idm_rot_filt.slcio -a
================ Component: filter_bunches ================
Error: Could not find or load main class org.hps.util.FilterMCBunches
Caused by: java.lang.ClassNotFoundException: org.hps.util.FilterMCBunches
hpsmc.job:INFO Execution of filter_bunches took 0.3157 second(s) with return code: 1
Traceback (most recent call last):
  File "/usr/local/lib/python/hpsmc/job.py", line 832, in <module>
    job.run()
  File "/usr/local/lib/python/hpsmc/job.py", line 516, in run
    self._execute()
  File "/usr/local/lib/python/hpsmc/job.py", line 574, in _execute
    raise Exception("Output file '%s' is missing after execution." % outputfile)
Exception: Output file 'idm_rot_filt.slcio' is missing after execution.
```
Just saving this so I don't forget about it.

**Comment by tomeichlersmith** [comment]
Even though java is complaining that it doesn't exist, it is still in the repo:
https://github.com/JeffersonLab/hps-java/blob/master/util/src/main/java/org/hps/util/FilterMCBunches.java

Going to replicate hps-prod in a denv and see if I can deduce why this is happening.

**Comment by tomeichlersmith** [comment]
I think the name has simply changed, for example
### with hps-java pin
```
#7 88.08 [INFO] Installing /usr/local/hps/java/plugin/target/hps-plugin-5.2.0.jar to /root/.m2/repository/org/hps/hps-plugin/5.2.0/hps-plugin-5.2.0.jar
```
### without pin
```
#7 97.40 [INFO] Installing /usr/local/hps/java/plugin/target/hps-plugin-5.2-SNAPSHOT.jar to /root/.m2/repository/org/hps/hps-plugin/5.2-SNAPSHOT/hps-plugin-5.2-SNAPSHOT.jar
```
Frankly, I'm surprised the error isn't "jar not found" or whatever. I don't know why a `5.2-SNAPSHOT` would even exist.

**Comment by tomeichlersmith** [comment]
So if its just a name change, I'll need to update

https://github.com/tomeichlersmith/hps-prod/blob/8f202a09bc21331405c3d2233d003bf7d4ebad78/context/Dockerfile#L15-L17

and

https://github.com/tomeichlersmith/hps-prod/blob/8f202a09bc21331405c3d2233d003bf7d4ebad78/context/container.cfg#L6-L7

**Comment by tomeichlersmith** [comment]
The `lcio` jar will stay as `SNAPSHOT` since `hps-lcio` is not having a version update.
